version: 2

builds:
  - id: mediaproxy
    binary: mediaproxy
    main: .
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - name_template: "mediaproxy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

dockers:
  - id: mediaproxy-amd64
    ids: [mediaproxy]
    image_templates:
      - "ghcr.io/skidoodle/mediaproxy:{{ .Version }}-amd64"
    dockerfile: Dockerfile.release
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    skip_push: false

docker_manifests:
  - name_template: "ghcr.io/skidoodle/mediaproxy:latest"
    image_templates:
      - "ghcr.io/skidoodle/mediaproxy:{{ .Version }}-amd64"
  - name_template: "ghcr.io/skidoodle/mediaproxy:{{ .Version }}"
    image_templates:
      - "ghcr.io/skidoodle/mediaproxy:{{ .Version }}-amd64"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
