services:
  mediaproxy:
    build: .
    container_name: mediaproxy
    ports:
      - "8080:8080"
    # restart: unless-stopped
    environment:
      - LOG_LEVEL=DEBUG
      # - CACHE_TTL=30m
      # - ALLOWED_DOMAINS=images.unsplash.com,static.pexels.com,*.example.com
      # - DEFAULT_IMAGE_QUALITY=100
      # - MAX_ALLOWED_SIZE=10485760
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'      # Limit to 50% of a single CPU core
    #       memory: '256M'   # Limit to 256 Megabytes of RAM
    #     reservations:
    #       cpus: '0.25'
    #       memory: '128M'
