services:
  mediaproxy:
    image: ghcr.io/skidoodle/mediaproxy:latest
    container_name: mediaproxy
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - LOG_LEVEL=INFO #(`DEBUG`, `INFO`, `WARN`, `ERROR`)
      # - BASE_URL=cdn.example.com #(middleware mode)
      # - CACHE_TTL=10m
      # - ALLOWED_DOMAINS=images.unsplash.com,*.example.com #(standard mode)
      # - MAX_ALLOWED_SIZE=52428800 # in bytes
      # - DEFAULT_IMAGE_QUALITY=80 # (1-100)
      # - CLIENT_TIMEOUT=2m
      # - ALLOW_PRIVATE_IPS=false
      # - TRUSTED_PROXIES=127.0.0.1,::1
