FROM alpine:latest AS sys
RUN apk add --no-cache ca-certificates vips tzdata && \
    addgroup -S mediaproxy && adduser -S mediaproxy -G mediaproxy && \
    rm -rf /bin/sh /bin/ash /bin/busybox /sbin/apk /etc/apk /lib/apk /var/cache/apk

FROM scratch
COPY --from=sys / /
COPY --chown=mediaproxy:mediaproxy mediaproxy /mediaproxy

USER mediaproxy
EXPOSE 3000
ENTRYPOINT ["/mediaproxy"]
