FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates libvips tzdata && \
    groupadd -r mediaproxy && useradd -r -g mediaproxy mediaproxy && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/* /bin/sh /bin/bash /usr/bin/apt* /usr/bin/dpkg*

COPY --chown=mediaproxy:mediaproxy mediaproxy /mediaproxy

USER mediaproxy
EXPOSE 3000
ENTRYPOINT ["/mediaproxy"]
