package app

import (
	"fmt"
	"net/http"
	"strings"
)

// sendError renders a structured plain-text error page.
// It retrieves the request ID from the context if available for tracking.
func sendError(w http.ResponseWriter, r *http.Request, statusCode int) {
	reqID := "unknown"
	if ctxID, ok := r.Context().Value(requestIDKey).(string); ok {
		reqID = ctxID
	}

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(statusCode)

	text := `%d %s

Request ID: %s
Generated by github.com/skidoodle/mediaproxy
`

	fmt.Fprintf(w, text, statusCode, strings.ToUpper(http.StatusText(statusCode)), reqID)
}
